AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: functionality for reviewing and correcting graph progress

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  OysterBedEndpoint:
    Type: String
    Description: the existing endpoint for the oyster bed for this task
  LambdaRoleArn:
    Type: String
    Description: the iam role used to run the lambda task
  GraphGqlEndpoint:
    Type: String
    Description: the endpoint for the graph data space

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.tasks.handler
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 600
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STATE: !Ref StorageBucket
  Oyster:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonOyster
        SemanticVersion: 0.0.44
      Parameters:
        IsDev: !Ref IsDev
        OysterBedEndpoint: !Ref OysterBedEndpoint
        LambdaRoleArn: !Ref LambdaRoleArn
        TaskFunctionArn: !GetAtt Task.Arn
        TaskName: "auditor"

Outputs:
  AuditorTaskArn:
    Description: the ARN of the auditor task
    Value: !GetAtt Task.Arn
  ListenerArn:
    Description: the ARN of the listener for this oyster
    Value: !GetAtt Oyster.Outputs.ShuckLineListener